# For connection urls to the following instances, see
# https://github.com/prisma/prisma/blob/main/TESTING.md#environment-variables
services:
  node:
    image: node:21-alpine
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev

  postgres:
    image: postgres:16
    restart: unless-stopped
    # Uncomment the following line to enable query logging
    # Then restart the container.
    command: ["postgres", "-c", "log_statement=all"]
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      # specifying user and database is needed to avoid `FATAL:  role "root" does not exist`
      # spam in the logs
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20

  metabase:
    image: metabase/metabase:latest
    ports:
      - ${METABASE_PORT}:3000
    healthcheck:
      test: curl --fail -I http://localhost:${METABASE_PORT}/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
